# Generated by Django 4.1.2 on 2023-01-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trayectos',
            new_name='Trayecto',
        ),
    ]
