# Generated by Django 4.1.2 on 2023-03-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distritos',
            new_name='Distrito',
        ),
    ]
