# Generated by Django 4.1.2 on 2023-02-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='movCon',
            field=models.CharField(default='000', max_length=20),
            preserve_default=False,
        ),
    ]
