# Generated by Django 4.1.2 on 2022-10-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='contactos',
        ),
        migrations.AddField(
            model_name='contactos',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminFCT.empresa'),
            preserve_default=False,
        ),
    ]
