# Generated by Django 4.1.2 on 2023-01-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0002_rename_trayectos_trayecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpsed', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminFCT.empresa')),
            ],
        ),
    ]
