# Generated by Django 4.1.2 on 2023-02-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0002_contacto_movcon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='profesor',
            name='empleado',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminFCT.empleado'),
            preserve_default=False,
        ),
    ]
