# Generated by Django 4.1.2 on 2023-03-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0003_alter_sede_cpsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='abre',
            field=models.CharField(max_length=100, unique=True, verbose_name='abreviación'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mailCon',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='movCon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='movil'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='finCon',
            field=models.DateField(blank=True, null=True, verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='iniCon',
            field=models.DateField(blank=True, null=True, verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pra',
            field=models.BooleanField(verbose_name='practica'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='cp',
            field=models.CharField(max_length=15, unique=True, verbose_name='codigo postal'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='distri',
            field=models.CharField(max_length=70, verbose_name='distrito'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='forma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminFCT.forma', verbose_name='forma'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nomEmp',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numTra',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='numero de trabajadores'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminFCT.ramo', verbose_name='rama'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminFCT.tamano', verbose_name='tamaño'),
        ),
        migrations.AlterField(
            model_name='forma',
            name='desFor',
            field=models.CharField(max_length=15, verbose_name='forma'),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='nomFun',
            field=models.CharField(max_length=100, verbose_name='funcion'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='conte',
            field=models.CharField(max_length=1000, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fmen',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='bibliotecas',
            field=models.ManyToManyField(to='adminFCT.funcion', verbose_name='funciones'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='competencias',
            field=models.ManyToManyField(to='adminFCT.perfil', verbose_name='Perfiles'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='especifaciones',
            field=models.ManyToManyField(to='adminFCT.requisito', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fofe',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='kas',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='dinero'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='nomOfe',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tele',
            field=models.BooleanField(verbose_name='teletrabajo'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='toolboxes',
            field=models.ManyToManyField(to='adminFCT.tool', verbose_name='Herramientas'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nomPer',
            field=models.CharField(max_length=100, verbose_name='perfil'),
        ),
        migrations.AlterField(
            model_name='practica',
            name='E',
            field=models.BooleanField(verbose_name='erasmus'),
        ),
        migrations.AlterField(
            model_name='practica',
            name='fFin',
            field=models.DateField(verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='practica',
            name='fIni',
            field=models.DateField(verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='practica',
            name='tele',
            field=models.BooleanField(verbose_name='teletrabajo'),
        ),
        migrations.AlterField(
            model_name='ramo',
            name='desRam',
            field=models.CharField(max_length=50, verbose_name='rama'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='nomReq',
            field=models.CharField(max_length=100, verbose_name='requisito'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='cpSed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminFCT.distrito', verbose_name='codigo postal'),
        ),
        migrations.AlterField(
            model_name='tamano',
            name='desTam',
            field=models.CharField(max_length=15, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='lenguaje',
            field=models.BooleanField(verbose_name='Lenguaje de programacion'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='nomToo',
            field=models.CharField(max_length=100, verbose_name='herramienta'),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='fpromo',
            field=models.DateField(blank=True, null=True, verbose_name='Promocion'),
        ),
    ]
