# Generated by Django 4.1.2 on 2023-02-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0003_remove_profesor_nombre_profesor_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='curri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fnac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='proy',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='finCon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='iniCon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminFCT.contacto'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminFCT.empresa'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fofe',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practica',
            name='fFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practica',
            name='fIni',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='fpromo',
            field=models.DateField(),
        ),
    ]
