# Generated by Django 4.1.2 on 2023-02-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0004_alter_alumno_curri_alter_alumno_fnac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fnac',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='finCon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='iniCon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fofe',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practica',
            name='fFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practica',
            name='fIni',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='fpromo',
            field=models.DateTimeField(),
        ),
    ]
