# Generated by Django 4.1.2 on 2023-01-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0004_rename_empresa_sede_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='fin',
            new_name='finCon',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='inicio',
            new_name='iniCon',
        ),
    ]
