# Generated by Django 4.1.2 on 2023-01-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0005_rename_fin_contrato_fincon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='emitido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emitido', to='adminFCT.empleado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='recibido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibido', to='adminFCT.empleado'),
        ),
    ]
