# Generated by Django 4.1.2 on 2023-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0005_alter_alumno_fnac_alter_contrato_fincon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fnac',
            field=models.DateField(),
        ),
    ]
