# Generated by Django 4.1.2 on 2023-01-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0006_mensaje_emitido_alter_mensaje_recibido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='contenido',
            new_name='conte',
        ),
    ]
