# Generated by Django 4.1.2 on 2023-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0007_alter_alumno_fnac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayecto',
            name='fpromo',
            field=models.DateField(),
        ),
    ]
