# Generated by Django 4.1.2 on 2023-01-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0007_rename_contenido_mensaje_conte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='nombre',
            new_name='nomEmp',
        ),
    ]
