# Generated by Django 4.1.2 on 2023-01-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0008_rename_nombre_empleado_nomemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practica',
            old_name='erasmus',
            new_name='E',
        ),
        migrations.RenameField(
            model_name='practica',
            old_name='fechaFin',
            new_name='fFin',
        ),
        migrations.RenameField(
            model_name='practica',
            old_name='fechaInicio',
            new_name='fIni',
        ),
    ]
