# Generated by Django 4.1.2 on 2023-02-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0008_alter_trayecto_fpromo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fnac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='finCon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='iniCon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fofe',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practica',
            name='fFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practica',
            name='fIni',
            field=models.DateField(blank=True, null=True),
        ),
    ]
