# Generated by Django 4.1.2 on 2023-01-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0009_rename_erasmus_practica_e_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='nombre',
            new_name='nomToo',
        ),
    ]
