# Generated by Django 4.1.2 on 2023-01-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0011_rename_nombre_requisito_nomreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcion',
            old_name='nombre',
            new_name='nomFun',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='nombre',
            new_name='nomPer',
        ),
    ]
