# Generated by Django 4.1.2 on 2023-02-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0013_rename_nombre_oferta_nomofe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='contacto',
            name='empleado',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminFCT.empleado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.FileField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='kas',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
