# Generated by Django 4.1.2 on 2023-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminFCT', '0014_remove_contacto_nombre_contacto_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mailCon',
            field=models.EmailField(max_length=254),
        ),
    ]
